chore(ci): add validation job to Lint-and-Test workflow, as umbrella/rollup check of matrix tests status

diff --git a/.github/workflows/lint-and-test.yml b/.github/workflows/lint-and-test.yml
--- a/.github/workflows/lint-and-test.yml
+++ b/.github/workflows/lint-and-test.yml
@@ -39,3 +39,17 @@ jobs:
         python: ${{ matrix.python }}
     - name: Test
       run: tox
+  validation:
+    name: Validation
+    runs-on: ubuntu-latest
+    needs: [test]
+    if: always()
+    steps:
+      - name: Validate matrix test success
+        run: |
+          # Check the status of the 'test' job (which includes all matrix variations)
+          if [ "${{ needs.test.result }}" != "success" ]; then
+            echo "One or more matrix test jobs failed."
+            exit 1
+          fi
+          echo "All matrix test jobs passed."
